Repository coactions/dynamic-matrix, pull requests merged in 2022-12, with the labels that each got.

#7 Improve readme
  .config/dictionary.txt
  README.md
Labels: bug

#9 Add setup python
  .github/workflows/tox.yml
Labels: skip-changelog

#8 Add max_python option
  action.yml
  entrypoint.py
Labels: enhancement
